### ISSUE TITLE
Variables are undefined

### ISSUE THREAD

**Issue by freddyp92** [UKHomeOffice/workstation_config#8]
TASK [facter : Storing username folder is present] - this task throws errors due to undefined variables, possibly because these variables are stored in a directory that is currently in the .gitignore file.

**Comment by freddyp92** [comment]
fatal: [dadmin-workstation.dsab-eud-xxx]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'node_path' is undefined\n\nThe error appears to have been in '/home/dadmin/GIT/workstation_config/roles/facter/tasks/main.yml': line 21, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Storing username folder is present\n  ^ here\n"}

**Comment by dogbonnahNB** [comment]
Due to the variables file containing sensitive data, the file containing variable is not committed to the repo. Each user of the application is expected to create their own variables file specific to their system. Further documentation will be provided later
